### ISSUE TITLE
Error: "CARDANO_NODE_SOCKET_PATH"

### ISSUE THREAD

**Issue by lucifer911** [armada-alliance/cardano-minter#1]
Hello,
Sorry i have no other way to contact you. I ran into an issue.
I think I am having trouble setting up the PATH. When i run  node src/get-balance.js I am getting this error.
<img width="1571" alt="Screen Shot 2021-04-14 at 2 04 20 PM" src="https://user-images.githubusercontent.com/27394137/114757818-511d6400-9d2a-11eb-80ca-17fa2823dcf4.png">
Can you plz guide me.
Thank you.

**Comment by AstroWa3l** [comment]
Socket is not showing in db, most likely need to restart your node and check db again, if you don't see socket I would delete db and redownloaded it as it may be corrupted.

**Comment by eastpiada** [comment]
@lucifer911 Try this from the command line:

> echo $CARDANO_NODE_SOCKET_PATH

If that doesn't return anything then the script you're trying to use won't be able to find your socket. It should be located somewhere like $NODE_HOME/db/socket or $CNODE_HOME/sockets/node0.socket - just depends on how your cardano-node install looks. $NODE_HOME might be something like /home/ada/pi-node or /opt/cardano/cnode for example.

You can set it from the command line and it'll be available for the duration of your session:
export CARDANO_NODE_SOCKET_PATH=$NODE_HOME/db/socket

Or add that export command above to your .bashrc file in your $HOME directory and you shouldn't have to mess with it again.
