### ISSUE TITLE
cardano-cli: not found

### ISSUE THREAD

**Issue by roman-HS** [armada-alliance/cardano-minter#4]
Hi guys,

I'm sorry for opening an issue but I haven't found any other way to contact you. I have been doing the tutorial but I'm having an issue when running the `create-wallet` file. Like it doesn't found `cardano-cli... I have installed both (cardano-cli & cardano node). I have even consoled out the object coming from your library `cardanocli-js` so I'm not sure what's happening. 

please see below the error I'm getting

<img width="2177" alt="Screen Shot 2021-07-07 at 6 57 45 PM" src="https://user-images.githubusercontent.com/68303463/124839141-3be55980-df56-11eb-8a2b-cb8f8fd37e23.png">

Can you please help me out?

**Comment by AstroWa3l** [comment]
Hi Roman, are you following the guide on our [website](https://docs.armada-alliance.com/learn/cardano-developer-guides/nft-native-assets) ? If so, why are you using sudo to run the wallet command?

After creating the wallet file you should actually change back to the "minter" directory not "src" and run the script. You should use this command:
```
node src/create-wallet.js
```

**Comment by roman-HS** [comment]
Hi, thanks for the reply.

Yes, I'm following the tutorial. I'm using sudo because I have cardano-node in a Linux VM (VirtualBox). Either way I don't think sudo is the root of the proble since I am able to run the other scripts up to that point.

About the location, I have tried running the script from the `minter` folder too and i get the same issue (I don;t think the location is neither the problem). Please see below the same error when I run the command from the minter folder.

<img width="2154" alt="Screen Shot 2021-07-08 at 8 19 59 AM" src="https://user-images.githubusercontent.com/68303463/124920961-e5176880-dfc5-11eb-82c5-24dd26d5b8b7.png">


Thanks

**Comment by ghost** [comment]
> Hi guys,
> 
> I'm sorry for opening an issue but I haven't found any other way to contact you. I have been doing the tutorial but I'm having an issue when running the `create-wallet` file. Like it doesn't found `cardano-cli... I have installed both (cardano-cli & cardano node). I have even consoled out the object coming from your library `cardanocli-js` so I'm not sure what's happening.
> 
> please see below the error I'm getting
> 
> <img alt="Screen Shot 2021-07-07 at 6 57 45 PM" width="2000" src="https://user-images.githubusercontent.com/68303463/124839141-3be55980-df56-11eb-8a2b-cb8f8fd37e23.png">
> 
> Can you please help me out?

the command in the code outdated: https://www.npmjs.com/package/cardanocli-js here, check out the getting started code to make appropriate changes.

**Comment by roman-HS** [comment]
> > Hi guys,
> > I'm sorry for opening an issue but I haven't found any other way to contact you. I have been doing the tutorial but I'm having an issue when running the `create-wallet` file. Like it doesn't found `cardano-cli... I have installed both (cardano-cli & cardano node). I have even consoled out the object coming from your library `cardanocli-js` so I'm not sure what's happening.
> > please see below the error I'm getting
> > <img alt="Screen Shot 2021-07-07 at 6 57 45 PM" width="2000" src="https://user-images.githubusercontent.com/68303463/124839141-3be55980-df56-11eb-8a2b-cb8f8fd37e23.png">
> > Can you please help me out?
> 
> the command in the code outdated: https://www.npmjs.com/package/cardanocli-js here, check out the getting started code to make appropriate changes. however i still am running into errors while attempting to mint tokens....i guess this code needs a revision


I have tried the new code and I'm still having the same issues when I try to run the `create-wallet` script (see below)


<img width="785" alt="Screen Shot 2021-07-08 at 10 20 05 AM" src="https://user-images.githubusercontent.com/68303463/124938748-8dcdc400-dfd6-11eb-9dab-e70dad3aa0f1.png">
<img width="1916" alt="Screen Shot 2021-07-08 at 10 20 37 AM" src="https://user-images.githubusercontent.com/68303463/124938751-8e665a80-dfd6-11eb-92f4-2238606fbe38.png">

<img width="457" alt="Screen Shot 2021-07-08 at 10 24 27 AM" src="https://user-images.githubusercontent.com/68303463/124938957-bc4b9f00-dfd6-11eb-99b1-9ed0c9ba15b9.png">

**Comment by AstroWa3l** [comment]
your Cardano node is fully synced to the blockchain, right?

**Comment by AstroWa3l** [comment]
@sublayerio any clue why they maybe are having an issue?

**Comment by kartheeksatya** [comment]
> > > Hi guys,
> > > I'm sorry for opening an issue but I haven't found any other way to contact you. I have been doing the tutorial but I'm having an issue when running the `create-wallet` file. Like it doesn't found `cardano-cli... I have installed both (cardano-cli & cardano node). I have even consoled out the object coming from your library `cardanocli-js` so I'm not sure what's happening.
> > > please see below the error I'm getting
> > > <img alt="Screen Shot 2021-07-07 at 6 57 45 PM" width="2000" src="https://user-images.githubusercontent.com/68303463/124839141-3be55980-df56-11eb-8a2b-cb8f8fd37e23.png">
> > > Can you please help me out?
> > 
> > 
> > the command in the code outdated: https://www.npmjs.com/package/cardanocli-js here, check out the getting started code to make appropriate changes. however i still am running into errors while attempting to mint tokens....i guess this code needs a revision
> 
> I have tried the new code and I'm still having the same issues when I try to run the `create-wallet` script (see below)
> 
> <img alt="Screen Shot 2021-07-08 at 10 20 05 AM" width="785" src="https://user-images.githubusercontent.com/68303463/124938748-8dcdc400-dfd6-11eb-9dab-e70dad3aa0f1.png">
> 
> <img alt="Screen Shot 2021-07-08 at 10 20 37 AM" width="1916" src="https://user-images.githubusercontent.com/68303463/124938751-8e665a80-dfd6-11eb-92f4-2238606fbe38.png">
> 
> <img alt="Screen Shot 2021-07-08 at 10 24 27 AM" width="457" src="https://user-images.githubusercontent.com/68303463/124938957-bc4b9f00-dfd6-11eb-99b1-9ed0c9ba15b9.png">

It says cardano-cli not found....have you installed cardano node 1.27 and cardano-cli  ...and ....the node up and running that is synced to the blockchain

**Comment by ghost** [comment]
> > > Hi guys,
> > > I'm sorry for opening an issue but I haven't found any other way to contact you. I have been doing the tutorial but I'm having an issue when running the `create-wallet` file. Like it doesn't found `cardano-cli... I have installed both (cardano-cli & cardano node). I have even consoled out the object coming from your library `cardanocli-js` so I'm not sure what's happening.
> > > please see below the error I'm getting
> > > <img alt="Screen Shot 2021-07-07 at 6 57 45 PM" width="2000" src="https://user-images.githubusercontent.com/68303463/124839141-3be55980-df56-11eb-8a2b-cb8f8fd37e23.png">
> > > Can you please help me out?
> > 
> > 
> > the command in the code outdated: https://www.npmjs.com/package/cardanocli-js here, check out the getting started code to make appropriate changes. however i still am running into errors while attempting to mint tokens....i guess this code needs a revision
> 
> I have tried the new code and I'm still having the same issues when I try to run the `create-wallet` script (see below)
> 
> <img alt="Screen Shot 2021-07-08 at 10 20 05 AM" width="785" src="https://user-images.githubusercontent.com/68303463/124938748-8dcdc400-dfd6-11eb-9dab-e70dad3aa0f1.png">
> 
> <img alt="Screen Shot 2021-07-08 at 10 20 37 AM" width="1916" src="https://user-images.githubusercontent.com/68303463/124938751-8e665a80-dfd6-11eb-92f4-2238606fbe38.png">
> 
> <img alt="Screen Shot 2021-07-08 at 10 24 27 AM" width="457" src="https://user-images.githubusercontent.com/68303463/124938957-bc4b9f00-dfd6-11eb-99b1-9ed0c9ba15b9.png">

I'm guessing cardano.js file doesn't have all inputs ...check out his client file (like dir)....and I suggest trying on testnet if this is your first time...so you don't risk your real ada

**Comment by AstroWa3l** [comment]
You shouldn't use sudo any where in the tutorial other than where we put it. So yeah it can be an issue. I don't not think it's the issue here either. But the location was an issue if your using those commands listed on the tutorial while in the src folder. 

Is your cardano node fully synched to the blockchain?

**Comment by roman-HS** [comment]
Yes, the cardano node is fully synced to the blockchain (see below). If I don't use sudo I got permission errors from VirtualBox. See below where one of the terminals has the command running on the same location as the tutorial.

<img width="2150" alt="Screen Shot 2021-07-09 at 4 26 43 PM" src="https://user-images.githubusercontent.com/68303463/125132786-d36fb700-e0d2-11eb-9481-1aa1628a472e.png">

**Comment by ghost** [comment]
> Yes, the cardano node is fully synced to the blockchain (see below). If I don't use sudo I got permission errors from VirtualBox. See below where one of the terminals has the command running on the same location as the tutorial.
> 
> <img alt="Screen Shot 2021-07-09 at 4 26 43 PM" width="2000" src="https://user-images.githubusercontent.com/68303463/125132786-d36fb700-e0d2-11eb-9481-1aa1628a472e.png">

Check your node version ( I'm not sure that's the problem...but still) I myself am using a virtual box ubuntu...the code worked just fine....also try cloning the repo code and running it ....in that way you might figure out wether it's the environment problem or the code itself
